language: python
dist: xenial
python:
  - "3.7"
addons:
  apt:
    packages:
      - pandoc
      - ffmpeg
install:
  - pip install -r requirements.txt
  - pip install -r ci/requirements.txt
script:
  - python -m sphinx . _build/ -b html
